name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Generate Prisma Client
      run: pnpm --filter @ewap/auth-service exec prisma generate
      
    - name: Build
      run: pnpm run -r build
      
    - name: Typecheck
      run: pnpm run -r typecheck
      
    - name: Run unit tests
      run: pnpm test

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: e2e/package-lock.json
        
    - name: Install dependencies
      working-directory: ./e2e
      run: npm ci
      
    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      working-directory: ./e2e
      run: npx playwright test
